### ISSUE TITLE
Filter for minimal filesize and filetype

### ISSUE THREAD

**Issue by neonmaus** [2000GHz/OfflineParty#52]
First of all thanks for this software, I have been looking for a downloader that can access the favourites of the pages for a long time

Would it be possible to implement a filter so that only files with a certain minimum file size are downloaded and only of a certain file type, i.e. videos or images?

For example: Only download videos and only if they are over 100MB in size

That would be a really great feature :)

**Comment by 2000GHz** [comment]
Done! Hope it works as expected! And thanks a bunch for the suggestion :)

**Comment by neonmaus** [comment]
Wow that was quick, thank you very much :)
It works really great and saves a lot of useless downloads
