### ISSUE TITLE
Full stop/period prevents the URL from being picked up

### ISSUE THREAD

**Issue by syrexw** [2000GHz/OfflineParty#57]
If there is a "." somewhere in the name of the of the URL there is an error for "no matching entries found". Is there a workaround?

**Comment by 2000GHz** [comment]
> If there is a "." somewhere in the name of the of the URL there is an error for "no matching entries found". Is there a workaround?

Hello! Could you post an example please? Thanks!

**Comment by syrexw** [comment]
https://coomer.su/onlyfans/user/jill.hardener
https://coomer.su/onlyfans/user/jessy.bunny.official

**Comment by 2000GHz** [comment]
Thanks, I'll take a look after work, in the meantime you could try looking for the username instead of the URL, so Jill.hardener or Jessy.bunny.official

**Comment by 2000GHz** [comment]
This was fixed with the release of [version 1.4.6](https://github.com/2000GHz/OfflineParty/releases/tag/v1.4.6), please take a look, and thank you for reporting the issue :)
