### ISSUE TITLE
Moving the location of date to front when creating folders

### ISSUE THREAD

**Issue by syrexw** [2000GHz/OfflineParty#58]
Hello,

as a feature request would it be possible to have an option or maybe as a default to have Dates in the created folder name moved to the front of the name for easier sorting? "2024-01-24POST-TITLE" instead of "POST-TITLE2024-01-24"

**Comment by 2000GHz** [comment]
Hello! Change is done and should be up soon, sorry for taking so long, work and personal projects got in the way :(
